### ISSUE TITLE
Error: Cannot find module './configs.json'

### ISSUE THREAD

**Issue by ryanivandsouza** [tfKamran/mail-unmerge#2]
Followed the steps mention in README.md. I get the below error

```
**D:\broadcast
>**mail-unmerge ./header.csv ./content-template.txt
module.js:471
    throw err;
    ^

Error: Cannot find module './configs.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.getConfiguration (C:\Users\ryand\AppData\Roaming\npm\node_modules\mail-unmerge\config-manager.js:12:25)
    at Object.<anonymous> (C:\Users\ryand\AppData\Roaming\npm\node_modules\mail-unmerge\emailer.js:3:45)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by tfKamran** [comment]
Did you install `mail-unmerge` globally? Or locally?

**Comment by ryanivandsouza** [comment]
Globally. I pasted the command from the readme.md. I'm on Windows 10.

npm install -g mail-unmerge

**Comment by tfKamran** [comment]
It has been tested before on Windows 10, will test the latest version on the same and will let you know.

**Comment by tfKamran** [comment]
It has been fixed in v2.0.3, please confirm the fix from your side whenever possible.

Thanks for reporting, I really appreciate it.

**Comment by tfKamran** [comment]
I'll close the issue once you confirm the fix.

**Comment by ryanivandsouza** [comment]
I think I got past that and entered the mail server details incorrectly. Now I'm getting the below. Anyway to update the mail server details?

```
D:\broadcast
>mail-unmerge header.csv content-template.txt
Password for your email address (won't be saved): **************
Attempting to send 2 emails, please wait...
**************\AppData\Roaming\npm\node_modules\mail-unmerge\node_modules\nodemailer\lib\mailer\index.js:45
        this.transporter.mailer = this;
                                ^

TypeError: Cannot create property 'mailer' on string 'exryan******a%40c********h.com:**************25@change'
    at Mail (**************\AppData\Roaming\npm\node_modules\mail-unmerge\node_modules\nodemailer\lib\mailer\index.js:45:33)
    at Object.module.exports.createTransport (**************\AppData\Roaming\npm\node_modules\mail-unmerge\node_modules\nodemailer\lib\nodemailer.js:46:14)
    at module.exports (**************\AppData\Roaming\npm\node_modules\mail-unmerge\emailer.js:6:34)
    at emails.forEach.email (**************\ryand\AppData\Roaming\npm\node_modules\mail-unmerge\batch-emailer.js:5:9)
    at Array.forEach (native)
    at module.exports (**************\AppData\Roaming\npm\node_modules\mail-unmerge\batch-emailer.js:4:12)
    at Converter.csv.fromFile.on.on (**************\AppData\Roaming\npm\node_modules\mail-unmerge\index.js:68:17)
    at emitOne (events.js:96:13)
    at Converter.emit (events.js:188:7)
    at **************\AppData\Roaming\npm\node_modules\mail-unmerge\node_modules\csvtojson\libs\core\Converter.js:80:14

```

**Comment by tfKamran** [comment]
You can manually modify/delete the configuration file that it saves at `~/.mail-unmerge-configs.json`.

And make sure you are using the latest version of mail-unmerge (v2.0.3).
